# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from qdarkstyle import load_stylesheet
import sys
from PyQt5.QtCore import Qt
import vtkmodules.all as vtk
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor
from vtkmodules.vtkCommonColor import vtkNamedColors
from vtkmodules.vtkRenderingCore import (
    vtkColorTransferFunction,
    vtkRenderer,
    vtkVolume,
    vtkVolumeProperty
)


class Ui_MainWindow(object):
    def __initWidget(self):
        """ 初始化小部件 """

        # 隐藏滚动条
        self.view1.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view1.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view2.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view2.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.view3.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

        # 以鼠标所在位置为锚点进行缩放
        self.view1.setTransformationAnchor(self.view1.AnchorUnderMouse)
        self.view2.setTransformationAnchor(self.view2.AnchorUnderMouse)
        self.view3.setTransformationAnchor(self.view3.AnchorUnderMouse)

        # 平滑缩放
        # self.pixmapItem.setTransformationMode(Qt.SmoothTransformation)
        # self.view.setRenderHints(QPainter.Antialiasing |
        #                          QPainter.SmoothPixmapTransform)

        # 设置场景
        # font = QtGui.QFont()
        # font.setFamily("Arial")
        # font.setPointSize(20)
        # self.scene1.addText('横断面', font)
        # self.scene2.addText('冠状面', font)
        # self.scene3.addText('矢状面', font)

        # self.view1.setScene(self.scene1)
        # self.view2.setScene(self.scene2)
        # self.view3.setScene(self.scene3)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1050)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        # QGraphicsScene
        self.scene1 = QtWidgets.QGraphicsScene(self.centralwidget)  # show picture
        self.view1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.view1.setMouseTracking(True)
        # self.setCentralWidget(self.centralwidget)
        # 有view就要有scene
        self.view1.setScene(self.scene1)
        self._color_background = QtGui.QColor('#000000')
        self.scene1.setBackgroundBrush(self._color_background)
        self.view1.setSceneRect(0, 0, 500, 420)
        self.view1.setGeometry(QtCore.QRect(9, 51, 506, 426))
        self.view1.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')

        self.scene2 = QtWidgets.QGraphicsScene(self.centralwidget)
        self.view2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.view2.setMouseTracking(True)
        # self.setCentralWidget(self.centralwidget)
        # 有view就要有scene
        self.view2.setScene(self.scene2)
        self._color_background = QtGui.QColor('#000000')
        self.scene2.setBackgroundBrush(self._color_background)
        self.view2.setSceneRect(0, 0, 500, 420)
        self.view2.setGeometry(QtCore.QRect(9, 511, 506, 426))
        self.view2.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')

        self.scene3 = QtWidgets.QGraphicsScene(self.centralwidget)
        self.view3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.view3.setMouseTracking(True)
        # self.setCentralWidget(self.centralwidget)
        # 有view就要有scene
        self.view3.setScene(self.scene3)
        self._color_background = QtGui.QColor('#000000')
        self.scene3.setBackgroundBrush(self._color_background)
        self.view3.setSceneRect(0, 0, 500, 420)
        self.view3.setGeometry(QtCore.QRect(529, 51, 506, 426))
        self.view3.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')

        self.__initWidget()

        self.menubar = QtWidgets.QMenuBar(self.centralwidget)
        # self.menubar.setGeometry(QtCore.QRect(2, 0, 1600, 38))
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu_image = QtWidgets.QAction("Load and Display(&Image)", self.menubar)
        self.menu_image.setObjectName("menu_image")
        self.menu_seg = QtWidgets.QAction("&Display segmentation results(&Mask)", self.menubar)
        self.menu_seg.setObjectName("menu_seg")

        self.menu_liverseg = QtWidgets.QAction("&Liver segmentation(&Liver)", self.menubar)
        self.menu_liverseg.setObjectName("menu_liverseg")
        self.menu_tumorseg = QtWidgets.QAction("&Spleen segmentation(&Spleen)", self.menubar)
        self.menu_tumorseg.setObjectName("menu_tumorseg")

        self.menubar.addAction(self.menu_image)
        # self.menubar.addMenu(self.menu_alternative)
        # self.menubar.addAction(self.menu_liverseg)  # 已移除
        # self.menubar.addAction(self.menu_tumorseg)  # 已移除
        self.menubar.addAction(self.menu_seg)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2000, 43))

        # Status
        self.bound_stat = QtWidgets.QLabel(self.centralwidget)
        self.bound_stat.setGeometry(QtCore.QRect(0, 970, 2000, 200))
        self.bound_stat.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_stat.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_stat.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_stat.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255);background-color: rgb(68, 83, 100);')
        self.bound_stat.setObjectName("bound_stat")

        self.statusbar = QtWidgets.QStatusBar(self.centralwidget)
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        self.statusbar.setFont(font)
        # self.statusbar.setAlignment(QtCore.Qt.AlignCLeft)
        self.statusbar.setObjectName("statusbar")
        self.statusbar.showMessage('Ready')
        self.statusbar.setGeometry(QtCore.QRect(0, 970, 2000, 40))

        # bound of Choose
        self.bound_choose = QtWidgets.QLabel(self.centralwidget)
        self.bound_choose.setGeometry(QtCore.QRect(1060, 686, 430, 250))
        self.bound_choose.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_choose.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_choose.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_choose.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')
        # 调整文字与边框的对齐，可以多试几个参数，比如AlignTop
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.bound_choose.setFont(font)
        self.bound_choose.setAlignment(QtCore.Qt.AlignHCenter)
        self.bound_choose.setObjectName("bound_choose")

        # bound of Preidct
        self.bound_predict = QtWidgets.QLabel(self.centralwidget)
        self.bound_predict.setGeometry(QtCore.QRect(1500, 52, 390, 884))
        self.bound_predict.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_predict.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')
        # 调整文字与边框的对齐，可以多试几个参数，比如AlignTop
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.bound_predict.setFont(font)
        self.bound_predict.setAlignment(QtCore.Qt.AlignHCenter)
        self.bound_predict.setObjectName("bound_predict")

        self.bound_predict2 = QtWidgets.QLabel(self.centralwidget)
        self.bound_predict2.setGeometry(QtCore.QRect(1060, 52, 430, 480))
        self.bound_predict2.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_predict2.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict2.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')
        # 调整文字与边框的对齐，可以多试几个参数，比如AlignTop
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.bound_predict2.setFont(font)
        self.bound_predict2.setAlignment(QtCore.Qt.AlignHCenter)
        self.bound_predict2.setObjectName("bound_predict2")

        self.bound_predict3 = QtWidgets.QLabel(self.centralwidget)
        self.bound_predict3.setGeometry(QtCore.QRect(1060, 540, 430, 136))
        self.bound_predict3.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_predict3.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_predict3.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255, 255);background-color: rgb(0, 0, 0, 0);')
        # 调整文字与边框的对齐，可以多试几个参数，比如AlignTop
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        self.bound_predict3.setFont(font)
        self.bound_predict3.setAlignment(QtCore.Qt.AlignHCenter)
        self.bound_predict3.setObjectName("bound_predict3")
        

        # bound of vface
        self.bound_vface = QtWidgets.QLabel(self.centralwidget)
        self.bound_vface.setGeometry(QtCore.QRect(529, 511, 506, 426))
        self.bound_vface.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_vface.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bound_vface.setFrameShape(QtWidgets.QFrame.Box)
        self.bound_vface.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255);background-color: rgb(0, 0, 0);')
        self.bound_vface.setObjectName("bound_vface")

        # Label "Load data"
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1507, 102, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.label_x1 = QtWidgets.QLabel(self.centralwidget)
        self.label_x1.setGeometry(QtCore.QRect(1077, 102, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x1.setFont(font)
        self.label_x1.setObjectName("label_x1")

        # Label ""
        self.label__1 = QtWidgets.QLabel(self.centralwidget)
        self.label__1.setGeometry(QtCore.QRect(1510, 142, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__1.setFont(font)
        self.label__1.setObjectName("label__1")

        # Label ""
        self.label__2 = QtWidgets.QLabel(self.centralwidget)
        self.label__2.setGeometry(QtCore.QRect(1510, 177, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__2.setFont(font)
        self.label__2.setObjectName("label__2")


        self.label__3 = QtWidgets.QLabel(self.centralwidget)
        self.label__3.setGeometry(QtCore.QRect(1520, 215, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__3.setFont(font)
        self.label__3.setObjectName("label__3")

        self.box1 = QtWidgets.QLineEdit(self.centralwidget)
        self.box1.setGeometry(QtCore.QRect(1755, 218, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box1.setFont(font)
        self.box1.setObjectName("box1")

        self.label__4 = QtWidgets.QLabel(self.centralwidget)
        self.label__4.setGeometry(QtCore.QRect(1520, 248, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__4.setFont(font)
        self.label__4.setObjectName("label__4")

        self.box2 = QtWidgets.QLineEdit(self.centralwidget)
        self.box2.setGeometry(QtCore.QRect(1755, 251, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box2.setFont(font)
        self.box2.setObjectName("box2")

        self.label__5 = QtWidgets.QLabel(self.centralwidget)
        self.label__5.setGeometry(QtCore.QRect(1520, 281, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__5.setFont(font)
        self.label__5.setObjectName("label__5")

        self.box3 = QtWidgets.QLineEdit(self.centralwidget)
        self.box3.setGeometry(QtCore.QRect(1755, 284, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box3.setFont(font)
        self.box3.setObjectName("box3")

        self.label__6 = QtWidgets.QLabel(self.centralwidget)
        self.label__6.setGeometry(QtCore.QRect(1520, 314, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__6.setFont(font)
        self.label__6.setObjectName("label__6")

        self.box4 = QtWidgets.QLineEdit(self.centralwidget)
        self.box4.setGeometry(QtCore.QRect(1755, 317, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box4.setFont(font)
        self.box4.setObjectName("box4")

        self.label__7 = QtWidgets.QLabel(self.centralwidget)
        self.label__7.setGeometry(QtCore.QRect(1520, 347, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__7.setFont(font)
        self.label__7.setObjectName("label__7")


        self.box5 = QtWidgets.QLineEdit(self.centralwidget)
        self.box5.setGeometry(QtCore.QRect(1755, 350, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box5.setFont(font)
        self.box5.setObjectName("box5")

        self.label__8 = QtWidgets.QLabel(self.centralwidget)
        self.label__8.setGeometry(QtCore.QRect(1520, 380, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__8.setFont(font)
        self.label__8.setObjectName("label__8")


        self.box6 = QtWidgets.QLineEdit(self.centralwidget)
        self.box6.setGeometry(QtCore.QRect(1755, 383, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box6.setFont(font)
        self.box6.setObjectName("box6")

        self.label__9 = QtWidgets.QLabel(self.centralwidget)
        self.label__9.setGeometry(QtCore.QRect(1520, 413, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__9.setFont(font)
        self.label__9.setObjectName("label__9")

        self.box7 = QtWidgets.QLineEdit(self.centralwidget)
        self.box7.setGeometry(QtCore.QRect(1755, 416, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box7.setFont(font)
        self.box7.setObjectName("box7")

        self.label__10 = QtWidgets.QLabel(self.centralwidget)
        self.label__10.setGeometry(QtCore.QRect(1520, 446, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__10.setFont(font)
        self.label__10.setObjectName("label__10")

        self.box8 = QtWidgets.QLineEdit(self.centralwidget)
        self.box8.setGeometry(QtCore.QRect(1755, 449, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box8.setFont(font)
        self.box8.setObjectName("box8")

        self.label__11 = QtWidgets.QLabel(self.centralwidget)
        self.label__11.setGeometry(QtCore.QRect(1520, 479, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__11.setFont(font)
        self.label__11.setObjectName("label__11")


        self.box9 = QtWidgets.QLineEdit(self.centralwidget)
        self.box9.setGeometry(QtCore.QRect(1755, 482, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box9.setFont(font)
        self.box9.setObjectName("box9")

        self.label__12 = QtWidgets.QLabel(self.centralwidget)
        self.label__12.setGeometry(QtCore.QRect(1520, 512, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__12.setFont(font)
        self.label__12.setObjectName("label__12")


        self.box10 = QtWidgets.QLineEdit(self.centralwidget)
        self.box10.setGeometry(QtCore.QRect(1755, 515, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box10.setFont(font)
        self.box10.setObjectName("box10")

        self.label__13 = QtWidgets.QLabel(self.centralwidget)
        self.label__13.setGeometry(QtCore.QRect(1520, 545, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__13.setFont(font)
        self.label__13.setObjectName("label__13")


        self.box11 = QtWidgets.QLineEdit(self.centralwidget)
        self.box11.setGeometry(QtCore.QRect(1755, 548, 110, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box11.setFont(font)
        self.box11.setObjectName("box11")

        self.label__14 = QtWidgets.QLabel(self.centralwidget)
        self.label__14.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label__14.hide()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__14.setFont(font)
        self.label__14.setObjectName("label__14")

        self.box12 = QtWidgets.QLineEdit(self.centralwidget)
        self.box12.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.box12.hide()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box12.setFont(font)
        self.box12.setObjectName("box12")

        self.label__15 = QtWidgets.QLabel(self.centralwidget)
        self.label__15.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label__15.hide()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__15.setFont(font)
        self.label__15.setObjectName("label__15")


        self.box13 = QtWidgets.QLineEdit(self.centralwidget)
        self.box13.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.box13.hide()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box13.setFont(font)
        self.box13.setObjectName("box13")

        self.label__16 = QtWidgets.QLabel(self.centralwidget)
        self.label__16.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label__16.hide()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__16.setFont(font)
        self.label__16.setObjectName("label__16")


        self.box14 = QtWidgets.QLineEdit(self.centralwidget)
        self.box14.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.box14.hide()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box14.setFont(font)
        self.box14.setObjectName("box14")

        self.label__17 = QtWidgets.QLabel(self.centralwidget)
        self.label__17.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.label__17.hide()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label__17.setFont(font)
        self.label__17.setObjectName("label__17")


        self.box15 = QtWidgets.QLineEdit(self.centralwidget)
        self.box15.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.box15.hide()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.box15.setFont(font)
        self.box15.setObjectName("box15")



        self.radiomics = QtWidgets.QPushButton(self.centralwidget)
        self.radiomics.setGeometry(QtCore.QRect(1360, 350, 110, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.radiomics.setFont(font)
        self.radiomics.setObjectName("radiomics")


        self.clincf_confirm = QtWidgets.QPushButton(self.centralwidget)
        self.clincf_confirm.setGeometry(QtCore.QRect(1525, 720, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.clincf_confirm.setFont(font)
        self.clincf_confirm.setObjectName("clincf_confirm")

        # Button "Clear factor"
        self.clearfactor = QtWidgets.QPushButton(self.centralwidget)
        self.clearfactor.setGeometry(QtCore.QRect(1745, 720, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.clearfactor.setFont(font)
        self.clearfactor.setObjectName("clearfactor")

        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1077, 232, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1080, 400, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.label_x2 = QtWidgets.QLabel(self.centralwidget)
        self.label_x2.setGeometry(QtCore.QRect(1080, 425, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_x2.setFont(font)
        self.label_x2.setObjectName("label_x2")

        self.label_x3 = QtWidgets.QLabel(self.centralwidget)
        self.label_x3.setGeometry(QtCore.QRect(1080, 450, 370, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_x3.setFont(font)
        self.label_x3.setObjectName("label_x3")

        self.label_x4 = QtWidgets.QLabel(self.centralwidget)
        self.label_x4.setGeometry(QtCore.QRect(1080, 475, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_x4.setFont(font)
        self.label_x4.setObjectName("label_x4")

        self.label_x7 = QtWidgets.QLabel(self.centralwidget)
        self.label_x7.setGeometry(QtCore.QRect(1090, 590, 370, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_x7.setFont(font)
        self.label_x7.setObjectName("label_x7")

        self.label_x8 = QtWidgets.QLabel(self.centralwidget)
        self.label_x8.setGeometry(QtCore.QRect(1085, 630, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x8.setFont(font)
        self.label_x8.setObjectName("label_x8")

        self.label_x9 = QtWidgets.QLabel(self.centralwidget)
        self.label_x9.setGeometry(QtCore.QRect(1197, 630, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x9.setFont(font)
        self.label_x9.setObjectName("label_x9")

        self.label_x10 = QtWidgets.QLabel(self.centralwidget)
        self.label_x10.setGeometry(QtCore.QRect(1080, 150, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x10.setFont(font)
        self.label_x10.setObjectName("label_x10")
    
        self.label_x11 = QtWidgets.QLabel(self.centralwidget)
        self.label_x11.setGeometry(QtCore.QRect(1215, 150, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x11.setFont(font)
        self.label_x11.setObjectName("label_x11")

        self.volume_lv = QtWidgets.QTextBrowser(self.centralwidget)
        self.volume_lv.setGeometry(QtCore.QRect(1223, 147, 130, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.volume_lv.setFont(font)
        self.volume_lv.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.volume_lv.setObjectName("volume_lv")


       
        self.calvolume_lv = QtWidgets.QPushButton(self.centralwidget)
        self.calvolume_lv.setGeometry(QtCore.QRect(1370, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(False)
        self.calvolume_lv.setFont(font)
        self.calvolume_lv.setObjectName("calvolume_lv")

        self.label_x12 = QtWidgets.QLabel(self.centralwidget)
        self.label_x12.setGeometry(QtCore.QRect(1080, 280, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x12.setFont(font)
        self.label_x12.setObjectName("label_x12")

        self.label_x13 = QtWidgets.QLabel(self.centralwidget)
        self.label_x13.setGeometry(QtCore.QRect(1233, 280, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x13.setFont(font)
        self.label_x13.setObjectName("label_x13")

        self.label_x14 = QtWidgets.QLabel(self.centralwidget)
        self.label_x14.setGeometry(QtCore.QRect(1077, 350, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x14.setFont(font)
        self.label_x14.setObjectName("label_x14")

        self.label_x15 = QtWidgets.QLabel(self.centralwidget)
        self.label_x15.setGeometry(QtCore.QRect(1505, 765, 375, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_x15.setFont(font)
        self.label_x15.setObjectName("label_x15")

        self.volume_sp = QtWidgets.QTextBrowser(self.centralwidget)
        self.volume_sp.setGeometry(QtCore.QRect(1237, 277, 130, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.volume_sp.setFont(font)
        self.volume_sp.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.volume_sp.setObjectName("volume_sp")


        self.caspolume_sp = QtWidgets.QPushButton(self.centralwidget)
        self.caspolume_sp.setGeometry(QtCore.QRect(1370, 280, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(False)
        self.caspolume_sp.setFont(font)
        self.caspolume_sp.setObjectName("caspolume_sp")

        self.distance = QtWidgets.QTextBrowser(self.centralwidget)
        self.distance.setGeometry(QtCore.QRect(1207, 627, 130, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.distance.setFont(font)
        self.distance.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.distance.setObjectName("distance")

        # Button "Clear distance"
        self.cleardistance = QtWidgets.QPushButton(self.centralwidget)
        self.cleardistance.setGeometry(QtCore.QRect(1365, 630, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.cleardistance.setFont(font)
        self.cleardistance.setObjectName("cleardistance")

        # Button "Predict"
        self.predict = QtWidgets.QPushButton(self.centralwidget)
        self.predict.setGeometry(QtCore.QRect(1520, 795, 180, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.predict.setFont(font)
        self.predict.setObjectName("predict")

        self.pic_box_vface = QtWidgets.QGroupBox(self.centralwidget)
        self.pic_box_vface.setGeometry(QtCore.QRect(530, 512, 504, 424))
        self.pic_box_vface.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0);')


        self.vtkWidget = QVTKRenderWindowInteractor(self.pic_box_vface)
        self.vtkWidget.setGeometry(QtCore.QRect(0, 0, 504, 424))
        self.ren = vtkRenderer()
        self.vtkWidget.GetRenderWindow().AddRenderer(self.ren)
        self.iren = self.vtkWidget.GetRenderWindow().GetInteractor()
        self.colors = vtkNamedColors()
        self.vtkpros = {}
        self.colors.SetColor('BkgColor', [0, 0, 0, 255])
        self.ren.SetBackground(self.colors.GetColor3d('BkgColor'))
        self.iren.Initialize()


        # Button "Load tumor segmentation"
        self.loadmask = QtWidgets.QPushButton(self.centralwidget)
        self.loadmask.setGeometry(QtCore.QRect(1370, 233, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setItalic(False)
        self.loadmask.setFont(font)
        self.loadmask.setObjectName("loadmask")


        # Button "Choose CAM slice"
        self.confirm_r_text = QtWidgets.QPushButton(self.centralwidget)
        self.confirm_r_text.setGeometry(QtCore.QRect(1370, 880, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.confirm_r_text.setFont(font)
        self.confirm_r_text.setObjectName("confirm_r_text")

        # Box of "Choose CAM slice"
        self.printdim_r = QtWidgets.QLineEdit(self.centralwidget)
        self.printdim_r.setGeometry(QtCore.QRect(1080, 884, 80, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.printdim_r.setFont(font)
        self.printdim_r.setObjectName("printdim_r")

        self.explain_CAM = QtWidgets.QLabel(self.centralwidget)
        self.explain_CAM.setGeometry(QtCore.QRect(1165, 888, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.explain_CAM.setFont(font)
        self.explain_CAM.setObjectName("explain_CAM")

        # Label "Slice of Gard-CAM CT"
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1073, 837, 350, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")

        # Label "Slice of original CT"
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1073, 747, 300, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        # Label "Macrovascular invasion risk:"
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1520, 860, 300, 30))
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        # Box of "Macrovascular invasion risk:" - 可编辑输入框
        self.plotresult = QtWidgets.QLineEdit(self.centralwidget)
        self.plotresult.setGeometry(QtCore.QRect(1700, 855, 170, 34))
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        self.plotresult.setFont(font)
        self.plotresult.setStyleSheet('border-width: 1px;border-style: solid;border-color: rgb(255, 255, 255);background-color: rgb(100, 70, 90);')
        self.plotresult.setObjectName("plotresult")

        # Button "Clear all"
        self.clesarall = QtWidgets.QPushButton(self.centralwidget)
        self.clesarall.setGeometry(QtCore.QRect(1745, 795, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.clesarall.setFont(font)
        self.clesarall.setObjectName("clesarall")

        # Box of "Displayed Axial Slice:"
        self.page = QtWidgets.QLineEdit(self.centralwidget)
        self.page.setGeometry(QtCore.QRect(450, 483, 70, 21))
        self.page.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.page.setText("")
        self.page.setObjectName("page")

        # Box of "Displayed Coronal Slice:"
        self.page2 = QtWidgets.QLineEdit(self.centralwidget)
        self.page2.setGeometry(QtCore.QRect(450, 943, 70, 21))
        self.page2.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.page2.setText("")
        self.page2.setObjectName("page2")

        # Box of "Displayed Sagittal Slice:"
        self.page3 = QtWidgets.QLineEdit(self.centralwidget)
        self.page3.setGeometry(QtCore.QRect(970, 483, 70, 21))
        self.page3.setStyleSheet('border-width: 0px;border-style: solid;border-color: rgb(255, 255, 255),;background-color: rgb(0, 0, 0, 0);')
        self.page3.setText("")
        self.page3.setObjectName("page3")

        # # Heatmap index
        # self.index = QtWidgets.QLabel(self.centralwidget)
        # self.index.setGeometry(QtCore.QRect(1037, 49, 80, 895))
        # self.index.setObjectName("index")

        # Label "Displayed Coronal Slice:"
        self.coronal_slice = QtWidgets.QLabel(self.centralwidget)
        self.coronal_slice.setGeometry(QtCore.QRect(300, 940, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.coronal_slice.setAlignment(QtCore.Qt.AlignRight)
        self.coronal_slice.setFont(font)
        self.coronal_slice.setObjectName("coronal_slice")

        # Label "Displayed Axial Slice:"
        self.axial_slice = QtWidgets.QLabel(self.centralwidget)
        self.axial_slice.setGeometry(QtCore.QRect(280, 480, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.axial_slice.setAlignment(QtCore.Qt.AlignRight)
        self.axial_slice.setFont(font)
        self.axial_slice.setObjectName("axial_slice")

        # Label "Displayed Sagittal Slice:"
        self.sagittal_slice = QtWidgets.QLabel(self.centralwidget)
        self.sagittal_slice.setGeometry(QtCore.QRect(820, 480, 151, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.sagittal_slice.setAlignment(QtCore.Qt.AlignRight)
        self.sagittal_slice.setFont(font)
        self.sagittal_slice.setObjectName("sagittal_slice")

        # Label "Displayed coordinate:"
        self.coord = QtWidgets.QLabel(self.centralwidget)
        self.coord.setGeometry(QtCore.QRect(535, 940, 490, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.coord.setAlignment(QtCore.Qt.AlignRight)
        self.coord.setFont(font)
        self.coord.setObjectName("coord")

        # Label "Reference threshold: 0.157"
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1520, 900, 280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        # Slider Button "Choose Image slice"
        self.slideroriginal = QtWidgets.QSlider(self.centralwidget)
        self.slideroriginal.setGeometry(QtCore.QRect(1080, 784, 390, 30))
        self.slideroriginal.setOrientation(QtCore.Qt.Horizontal)
        self.slideroriginal.setObjectName("slideroriginal")


        # Label "Load clinical factor"
        self.loadclion = QtWidgets.QPushButton(self.centralwidget)
        self.loadclion.setGeometry(QtCore.QRect(1815, 142, 50, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.loadclion.setFont(font)
        self.loadclion.setObjectName("loadclion")


        # Button "Load liver segmentation"
        self.loadlivmask = QtWidgets.QPushButton(self.centralwidget)
        self.loadlivmask.setGeometry(QtCore.QRect(1370, 103, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.loadlivmask.setFont(font)
        self.loadlivmask.setObjectName("loadlivmask")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.confirm_r_text.clicked.connect(MainWindow.readnumresult)
        self.loadmask.clicked.connect(MainWindow.loadmaskf)
        self.loadclion.clicked.connect(MainWindow.showclion)
        self.loadlivmask.clicked.connect(MainWindow.loadlivermaskf)
        self.predict.clicked.connect(MainWindow.predictf)
        self.radiomics.clicked.connect(MainWindow.radiomics_link)
        self.calvolume_lv.clicked.connect(MainWindow.cal_liver)
        self.caspolume_sp.clicked.connect(MainWindow.cal_spleen)
        self.slideroriginal.valueChanged.connect(MainWindow.slideroriginal_function)
        self.clesarall.clicked.connect(MainWindow.clearallf)
        self.cleardistance.clicked.connect(MainWindow.cleardistancef)
        self.clearfactor.clicked.connect(MainWindow.clearfactorf)
        self.clincf_confirm.clicked.connect(MainWindow.clinicf_read)
        self.menu_image.triggered.connect(MainWindow.showpic)
        self.menu_seg.triggered.connect(MainWindow.show_mask)
        self.menu_liverseg.triggered.connect(MainWindow.liver_seg)
        self.menu_tumorseg.triggered.connect(MainWindow.tumor_seg)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OHE_Prediction"))
        self.predict.setText(_translate("MainWindow", "Start Prediction"))
        self.bound_predict.setText(_translate("MainWindow", "OHE Prediction(2)"))
        self.bound_predict2.setText(_translate("MainWindow", "OHE Prediction(1)"))
        self.bound_predict3.setText(_translate("MainWindow", "Distance Measurement"))
        self.bound_choose.setText(_translate("MainWindow", "Edit Images/Masks"))
        self.loadmask.setText(_translate("MainWindow", "Load"))
        self.calvolume_lv.setText(_translate("MainWindow", "Compute"))
        self.caspolume_sp.setText(_translate("MainWindow", "Compute"))
        self.confirm_r_text.setText(_translate("MainWindow", "Confirm"))
        self.label.setText(_translate("MainWindow", "Adjust the transparency of the mask"))
        self.label_2.setText(_translate("MainWindow", "Enlarge the image"))
        self.label_3.setText(_translate("MainWindow", "The risk of OHE:"))
        self.clesarall.setText(_translate("MainWindow", "Reload"))
        self.loadlivmask.setText(_translate("MainWindow", "Load"))
        self.radiomics.setText(_translate("MainWindow", "Compute"))
        self.clincf_confirm.setText(_translate("MainWindow", "Confirm"))
        self.clearfactor.setText(_translate("MainWindow", "Clear"))
        self.label_13.setText(_translate("MainWindow", "(*) Required, (#) Optional"))
        self.label_x2.setText(_translate("MainWindow", "Liver volume + Spleen volume"))
        self.label_x3.setText(_translate("MainWindow", "= Total hepatosplenic volume"))
        self.label_x4.setText(_translate("MainWindow", ""))
        self.label_x7.setText(_translate("MainWindow", "5. Select 2 points to measure distance"))
        self.label_x8.setText(_translate("MainWindow", "Distance:"))

        self.axial_slice.setText(_translate("MainWindow", "Displayed axial slice:"))
        self.coronal_slice.setText(_translate("MainWindow", "Displayed coronal slice:"))
        self.sagittal_slice.setText(_translate("MainWindow", "Displayed sagittal slice:"))
        self.coord.setText(_translate("MainWindow", "Welcome to use! "))
        self.label_6.setText(_translate("MainWindow", "(Reference threshold:0.556)"))
        # self.label_8.setText(_translate("MainWindow", "肿瘤异质性得分:"))
        # self.label_7.setText(_translate("MainWindow", "参考阈值:0.709"))
        self.loadclion.setText(_translate("MainWindow", "Load"))
        self.label_11.setText(_translate("MainWindow", "4. Load clinical factors (*)"))
        self.label_x1.setText(_translate("MainWindow", "1. Load liver mask (#)"))
        self.label_12.setText(_translate("MainWindow", "2. Load Spleen mask(#)"))
        self.label__1.setText(_translate("MainWindow", "Optaion(1)：Load CSV file"))
        self.label__2.setText(_translate("MainWindow", "Optaion(2)：Input clinical factors"))
        self.label__3.setText(_translate("MainWindow", "Age:"))
        self.label__4.setText(_translate("MainWindow", "Sodium (Na.B):"))
        self.label__5.setText(_translate("MainWindow", "APRI:"))
        self.label__6.setText(_translate("MainWindow", "Child-Pugh Score:"))
        self.label__7.setText(_translate("MainWindow", "Creatinine Conversion:"))
        self.label__8.setText(_translate("MainWindow", "Splenic Vein (SV):"))
        self.label__9.setText(_translate("MainWindow", "Portal Vein Diameter:"))
        self.label__10.setText(_translate("MainWindow", "SFVS CT Change Rate:"))
        self.label__11.setText(_translate("MainWindow", "Median Angle SFVS:"))
        self.label__12.setText(_translate("MainWindow", "GRS Diameter:"))
        self.label__13.setText(_translate("MainWindow", "Paraumbilical Vein:"))
        self.label__14.setText(_translate("MainWindow", ""))
        self.label__15.setText(_translate("MainWindow", ""))
        self.label_x9.setText(_translate("MainWindow", "___________"))
        self.label_x10.setText(_translate("MainWindow", "Liver volume:"))
        self.label_x11.setText(_translate("MainWindow", "___________"))
        self.label_x12.setText(_translate("MainWindow", "Spleen volume:"))
        self.label_x13.setText(_translate("MainWindow", "_________"))
        self.label_x14.setText(_translate("MainWindow", "3. Calculate radiomics(#)"))
        self.label_x15.setText(_translate("MainWindow", "-------------------------------------------------------------------"))
        self.cleardistance.setText(_translate("MainWindow", "Clear"))
        self.explain_CAM.setText(_translate("MainWindow", "Input a number in [0,1]"))